name: "GLaDOS Auto Checkin"

on:
    schedule:
        - cron: "01 16 * * *"

jobs:
    bot:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout codes"
              uses: actions/checkout@v2
            - name: "Setup python"
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Cache pip
              uses: actions/cache@v2
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
                      ${{ runner.os }}-
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: "Run script"
              env:
                  GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
                  SERVER_SCKEY: ${{ secrets.SERVER_SCKEY }}
              run: python checkin.py
